SELECT DATE_FORMAT(SALES_DATE, "%Y") as YEAR, 
DATE_FORMAT(SALES_DATE, "%m") as MONTH,
COUNT(DISTINCT(A.USER_ID)) as PUCHASED_USERS,
ROUND(COUNT(DISTINCT(A.USER_ID))/
      (select COUNT(*) from USER_INFO where JOINED like "2021-%"),1)
      as PUCHASED_RATIO
from USER_INFO A
join ONLINE_SALE B on A.USER_ID = B.USER_ID
where A.JOINED like "2021-%"
group by MONTH
order by YEAR, MONTH
