SELECT CONCAT('/home/grep/src/', BOARD_ID,'/',FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
    SELECT A.BOARD_ID
    FROM USED_GOODS_BOARD A
    JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
    ORDER BY A.VIEWS DESC
    LIMIT 1
)
ORDER BY FILE_ID DESC
